// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressiveWebAppBlog.Repository;

namespace ProgressiveWebAppBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190916234655_Iniciaç")]
    partial class Iniciaç
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");
#pragma warning restore 612, 618
        }
    }
}
